Check if ASSETS_DIR exists before sync assets
10up/action-wordpress-plugin-asset-update pull request #48
Opened 2023-02-09 06:56 UTC by azizultex

**Problem:** 
Sometimes we may want to push readme.txt file only and not create any .wordpress-org at all. I had this situation when I was just planning to update readme.txt and didn't create any .wordpress-org folder. But faced error: No such file or directory. 

**Solution would be like**
Check if ASSETS_DIR exists before running 
`rsync -rc "$GITHUB_WORKSPACE/$ASSETS_DIR/" assets/ --delete --delete-excluded` in the line 109. 

```
if [ -d "$GITHUB_WORKSPACE/$ASSETS_DIR" ]; then
    rsync -rc "$GITHUB_WORKSPACE/$ASSETS_DIR/" assets/ --delete --delete-excluded
fi
```

This should fix the error in the screenshot below. 

**Designs**
![image](https://user-images.githubusercontent.com/6356552/217604453-935f00dd-cad7-4aac-a649-56685187b9e2.png)

2023-02-09 13:35 UTC, cadic commented
The action expects `.wordpress-org` (or any other assets directory) to exist by default, so this error looks like the correct behaviour.

With the proposed change, I see the potential workflow which will break the logic:
- F.e. someone decide to change the assets directory from `.wordpress-org` to something else, like `.wordpress-assets`
- They might update the setting with a mistake `ASSETS_DIR=.wordpress-asserts`
- The action will skip non-existing directory with no error, while it should inform repo owner something is wrong

At other hand, if we want to skip `assets` directory update to the SVN, maybe it's a good idea to add a new setting `SKIP_ASSETS` which will tell the action that this step is not required.

2023-02-10 13:00 UTC, cadic requested changes
As for my prior comment https://github.com/10up/action-wordpress-plugin-asset-update/pull/48#issuecomment-1424201627

2023-02-11 07:08 UTC, azizultex commented
Yes. Adding a new setting SKIP_ASSETS is a good idea I think.

2023-04-11 09:21 UTC, Sidsector9 approved these changes, later dismissed
Thanks for the PR! LGTM 👍

2023-04-11 16:59 UTC, jeffpaul commented
@azizultex mind adding that new option to the readme file as well so folks are aware that's available?

2023-04-24 09:15 UTC, Sidsector9 approved these changes

2023-04-26 18:56 UTC, merged